/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\models\icosphere.glb -o .\src\components\models\IcoSphere\index.tsx 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    IcosphereNew: THREE.Mesh;
  };
  materials: {
    base: THREE.MeshStandardMaterial;
  };
};

export default function Model({
  children,
  color = "white",
  roughness = 0,
  ...props
}: any) {
  const { nodes, materials } = useGLTF(
    "/models/icosphere.glb"
  ) as unknown as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        scale={0.8}
        geometry={nodes.IcosphereNew.geometry}
        material={materials.base}
        castShadow
        receiveShadow
      >
        <meshStandardMaterial
          color={color}
          metalness={0.2}
          roughness={roughness}
          map={materials.base.map}
        />
        {children}
      </mesh>
    </group>
  );
}

useGLTF.preload("/models/icosphere.glb");
